cc_binary(name = 'add_person',
          srcs = ['add_person.cc',],
          deps = [
                  '//codelab/protobuf/proto:addressbook_proto',
                 ]
          )

cc_binary(name = 'list_people',
          srcs = ['list_people.cc',],
          deps = [
                  '//codelab/protobuf/proto:addressbook_proto',
                  ]
          )
