# Copyright 2012. All Rights Reserved.
# Author: yeshunping@gmail.com (Shunping Ye)
#
# Description:
#   TODO(shunpingye): describe this package.

cc_test(name = 'memory_leak_test',
        srcs = ['memory_leak_test.cc', ],
        deps = [
                '//thirdparty/glog:glog',
                '//thirdparty/gflags:gflags',
               ],
        heap_check = 'normal',
)
